module.exports = [
    { name: "Acrobatics", attr: "Dex"},
    { name: "Animal Handling", attr: "Wis"},
    { name: "Arcana", attr: "Int"},
    { name: "Athletics", attr: "Str"},
    { name: "Deception", attr: "Cha"},
    { name: "History", attr: "Int"},
    { name: "Insight", attr: "Wis"},
    { name: "Intimidation", attr: "Cha"},
    { name: "Investigation", attr: "Int"},
    { name: "Medicine", attr: "Wis"},
    { name: "Nature", attr: "Int"},
    { name: "Perception", attr: "Wis"},
    { name: "Performance", attr: "Cha"},
    { name: "Persuasion", attr: "Cha"},
    { name: "Religion", attr: "Int"},
    { name: "Sleight of Hand", attr: "Dex"},
    { name: "Stealth", attr: "Dex"},
    { name: "Survival", attr: "Wis"},
]